version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes: 
      - /app/node_modules
      - .:/app
    command: yarn serve

  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    environment: 
      - CI=true
    command: yarn test:unit